### ISSUE TITLE
Scalar: Floating point exception

### ISSUE THREAD

**Issue by cschol** [VCVRack/Rack#1100]
Operating system(s): Ubuntu 18.04
Version of Rack: 0.6.2b

- Add Scalar plugin to Rack
- Switch NOTES to 2
- Select second note, reduce cents a little (e.g. 550)
- Select first note
- Left-click on OCTAVES to switch from variable to shared
- Left-click on TUNING to switch to equal
- Right-click on CENTS, **FLOATING POINT EXCEPTION** occurs

Stacktrace:
```
Program terminated with signal SIGFPE, Arithmetic exception.
#0  0x00007f56e3359b33 in NoteBox::step() () from /home/cschol/.Rack/plugins/VCV-Scalar/plugin.so
[Current thread is 1 (Thread 0x7f56eeca7a00 (LWP 5699))]
(gdb) bt
#0  0x00007f56e3359b33 in NoteBox::step() () at /home/cschol/.Rack/plugins/VCV-Scalar/plugin.so
#1  0x0000559de0868e2f in rack::Widget::step() (this=0x559de23fbc00) at src/widgets/Widget.cpp:105
#2  0x0000559de0868e2f in rack::Widget::step() (this=0x559de23f8748) at src/widgets/Widget.cpp:105
#3  0x0000559de0868e2f in rack::Widget::step() (this=0x559de2351800) at src/widgets/Widget.cpp:105
#4  0x0000559de0868e2f in rack::Widget::step() (this=0x559de2333db0) at src/widgets/Widget.cpp:105
#5  0x0000559de0868e2f in rack::Widget::step() (this=this@entry=0x559de1f4d1d0) at src/widgets/Widget.cpp:105
#6  0x0000559de085b204 in rack::RackWidget::step() (this=<optimized out>) at src/app/RackWidget.cpp:497
#7  0x0000559de0868e2f in rack::Widget::step() (this=0x559de2333d00) at src/widgets/Widget.cpp:105
#8  0x0000559de0868e2f in rack::Widget::step() (this=0x559de2355b50) at src/widgets/Widget.cpp:105
#9  0x0000559de0868e2f in rack::Widget::step() (this=0x559de2333be8) at src/widgets/Widget.cpp:105
#10 0x0000559de0815022 in rack::ScrollWidget::step() (this=0x559de2333bc0) at src/ui/ScrollWidget.cpp:75
#11 0x0000559de0868e2f in rack::Widget::step() (this=0x559de2334610) at src/widgets/Widget.cpp:105
#12 0x0000559de0835cc6 in rack::RackScene::step() (this=0x559de23345f0) at src/app/RackScene.cpp:41
#13 0x0000559de080e57e in rack::windowRun() () at src/window.cpp:484
#14 0x0000559de0792dc6 in main(int, char**) (argc=<optimized out>, argv=<optimized out>) at src/main.cpp:107
```

**Comment by AndrewBelt** [comment]
Same issue as #1099
