### ISSUE TITLE
Logger causes Segfaults on Windows 10

### ISSUE THREAD

**Issue by GarfID** [VCVRack/Rack#1648]
### Details

Operating system: Windows 10 x64
Rack version: v1.1.6
Hardware relevant to your issue (e.g. graphic card model, audio/MIDI device): None

### Summary

When built on Windows 10 with use of MinGW64 logger function logVa(*) in logger.cpp causes ntdll.dll to trigger.

Stacktrace:
#0  0x00007ffeb535b40d in ntdll!RtlEnterCriticalSection ()
   from C:\WINDOWS\SYSTEM32\ntdll.dll
#1  0x000000000073e737 in __mingw_vfprintf (stream=0x0,
    fmt=fmt@entry=0x79a902 <stbi_zlib_compress(unsigned char*, int, int*, int)::lengthc+4034> "[%.03f %s %s:%d] ", argv=argv@entry=0x50bfc70 "")
    at E:/mingwbuild/mingw-w64-crt-git/src/mingw-w64/mingw-w64-crt/stdio/mingw_vfprintf.c:53
#2  0x000000000074c41d in fprintf (__stream=<optimized out>,
    __format=__format@entry=0x79a902 <stbi_zlib_compress(unsigned char*, int, int*, int)::lengthc+4034> "[%.03f %s %s:%d] ")
    at C:/msys64/mingw64/x86_64-w64-mingw32/include/stdio.h:341
#3  0x000000000047b51a in rack::logger::logVa (args=0x50bfd00 "▒\025▒",
    format=0x797e07 <ntryh+1287> "%s v%s", line=120,
    filename=0x797d71 <ntryh+1137> "src/main.cpp",
    level=rack::logger::INFO_LEVEL) at src/logger.cpp:57
#4  rack::logger::log (level=level@entry=rack::logger::INFO_LEVEL,
    filename=filename@entry=0x797d71 <ntryh+1137> "src/main.cpp",
    line=line@entry=120, format=format@entry=0x797e07 <ntryh+1287> "%s v%s")
    at src/logger.cpp:70
#5  0x00000000007838b1 in main (argc=1, argv=0x5ba2730)
    at C:/msys64/mingw64/include/c++/9.2.0/bits/basic_string.h:2300

Further inspection revealed that root functions of problem are fprintf(*) and vfprintf(*)

### Steps to reproduce

Build Rack from source.
Launch it without debugging argument.
The application freezes in background state

**Comment by AndrewBelt** [comment]
There's not enough information here to see what's going on. Could you attach your log.txt file from the Rack user directory?
