### ISSUE TITLE
helper.py fails to create components if shapes only have fill property

### ISSUE THREAD

**Issue by RCameron93** [VCVRack/Rack#1779]
I was trying to create a panel using an SVG file that originated in Adobe Illustrator. I had saved it again using Inkscape with all the proper labelling but I kept getting an error when I used helper.py

```
Traceback (most recent call last):
  File "/Users/Ross/Documents/rackDev/Rack-SDK/helper.py", line 531, in <module>
    parse_args(sys.argv)
  File "/Users/Ross/Documents/rackDev/Rack-SDK/helper.py", line 522, in parse_args
    create_module(*args)
  File "/Users/Ross/Documents/rackDev/Rack-SDK/helper.py", line 233, in create_module
    components = panel_to_components(tree)
  File "/Users/Ross/Documents/rackDev/Rack-SDK/helper.py", line 294, in panel_to_components
    color = color_match.group(1).lower()
AttributeError: 'NoneType' object has no attribute 'group'
```

Line 293 and 294 of helper.py:
```
color_match = re.search(r'fill:\S*#(.{6});', style)
color = color_match.group(1).lower()
```
The issue seems to be that Illustrator saved the SVG file with _just_ a fill property in the circles style tag. When it was saved again in Inkscape it didn't add anything to the tag either. The result was that, as there were no properties coming after it, there was no semi-colon at the end of the fill property, so re.search() couldn't find anything. 

Going into the SVG file with a text editor and manually adding semi-colons to the end of the fill properties solved the problem.
```
<circle
   id="circle291"
   style="fill:#ff0000;"
   r="9.6999998"
   cy="101.78"
   cx="96.660004"
   inkscape:label="fine" />
```

**Comment by starakaj** [comment]
The semicolon issue bit me too, with an illustrator export. But I think there are other problems with the regular expression, for example \S matches non-whitespace characters (probably \s was intended), so the color won't match if there are spaces between the colon and the # character. Also, illustrator likes to get clever and will call `#ff0000` "red". This patch addresses these issues.

[rack-color.patch.zip](https://github.com/VCVRack/Rack/files/6616435/rack-color.patch.zip)
