### ISSUE TITLE
helper.py createmodule failing to create .cpp files: Windows 10 - Mingw shell

### ISSUE THREAD

**Issue by StuLast** [VCVRack/Rack#1809]
### Details
Environment:
Windows 10 Professional
Mingw 64 shell
VS Code editor/IDE

Rack version (vX.Y.Z): Rack-SDK 1.1.16
Rack folder aliased to $RACK_SDK in both Windows Environment System Variables and Mingw 64 shell .bashrc file.

Hardware:
AMD Ryzen 7 3700X 8- core Processor clocked to 4.3 Mhz.
16GB RAM

### Summary
On executing createmodule from helper.py, process fails to create module.cpp file. with following in terminal:

```
$RACK_SDK/helper.py createmodule MyModule res/MyModule.svg src/MyModule.cpp
Module name [MyModule]: MyModule
One-line description (optional) []: VCO Module
Tags (comma-separated, case-insensitive, see https://github.com/VCVRack/Rack/blob/v1/src/tag.cpp for list) []: VCO
Added MyModule to plugin.json
Panel found at res/MyModule.svg. Generating source file.
Traceback (most recent call last):
  File "E:/Rack-SDK/helper.py", line 531, in <module>
    parse_args(sys.argv)
  File "E:/Rack-SDK/helper.py", line 522, in parse_args
    create_module(*args)
  File "E:/Rack-SDK/helper.py", line 231, in create_module
    tree = xml.etree.ElementTree.parse(panel_filename)
  File "C:/msys64/mingw64/lib/python3.8/xml/etree/ElementTree.py", line 1202, in parse
    tree.parse(source, parser)
  File "C:/msys64/mingw64/lib/python3.8/xml/etree/ElementTree.py", line 595, in parse
    self._root = parser._parse_whole(source)
xml.etree.ElementTree.ParseError: XML or text declaration not at start of entity: line 2, column 0
```

### Steps to reproduce
1.  Download and install MSys2. In my example on C:/

2.   Download and install VS Code.

3.  Add C/C++ extension to VS Code.

4.  Open Mingw 64 shell and update then restart shell.
```
pacman -Syu
```

5.  Add required libs via Mingw 64 shell then restart shell.
```
pacman -Su git wget make tar unzip zip mingw-w64-x86_64-gcc mingw-w64-x86_64-gdb mingw-w64-x86_64-cmake autoconf automake mingw-w64-x86_64-libtool mingw-w64-x86_64-jq python
```

6. Download and extract Rack-SDK to  Rack-SDK folder onto working drive (in my case E:\Rack-SDK)

7.  Open .bashrc from msys64/home/<user> and add the following to the bottom of the file, then save and restart shell.  Note that RACK-SDK is installed on E drive in my example.
```
export RACK_SDK=E:/RACK-SDK
```

8.  Edit Windows System Environment Variables to add new RACK_SDK to point to E:/RACK-SDK

9.  Open up Mingw64 shell.  Navigate to projects folder to create a new project and enter the following:
``` $RACK_SDK/helper.py createplugin MyPlugin```

10.  In VS Code  open plugin.cpp.  Find #include "plugin.hpp" which will have an "include error".  Click on the lightbulb at the bottom left of the error and select "Edit includePath setting".  This will create a new .vscode folder in the root of the project, with a c_cpp_properties.json file.

11.  It will also open a tab C/C++ configurations.  Close this tab and directly edit the c_cpp_properties.json file by adding the RACK_SDK to the include path array (or whatever your environment variable/path to Rack-SDK is)
```
            "includePath": [
                "${workspaceFolder}/**",
                "${RACK_SDK}/**"
            ],
```

12. From Mingw64 shell,  navigate to MyPlugin folder and build plugin:
```make```.  This should confirm all include paths are set correctly and create a plugin.dll file at the root of the project.
```
make
g++ -o plugin.dll build/src/plugin.cpp.o -shared -LE:/RACK-SDK -lRack

```

13.  Go [https://vcvrack.com/manual/_static/MyModule.svg].  DO NOT EDIT THIS FILE. Download this file directly to 
 ./res/MyModule.svg in your project root.

14.  In Mingw64, ensure you're in the root of your MyPlugin folder and execute
```RACK_SDK/helper.py createmodule MyModule res/MyModule.svg src/MyModule.cpp```

It's at this point the panel is found, but the .cpp source file fails to generate

**Comment by StuLast** [comment]
I've done some further investigation on this.  Setting up the project to work with Windows Subsystem For Linux(WSL), in my case a Debian WSL and executing the commands from within the WSL terminal succesfully creates the module.cpp file. Setting up a Debian WSL only requires the /mnt/your-drives/project-and-sdk-folders are symlinked to your home folder, and that your own debian .bashrc file is also configured with an exported alias, for example RACK_SDK="path-to-symlinked-Rack-SDK-Folder"

**Comment by StuLast** [comment]
Resolved - Problem Existed between chair and keyboard.

This was caused by  a simple error in naming the system variable in Windows Environment Settings.
