### ISSUE TITLE
Template suddenly makes VCV crash

### ISSUE THREAD

**Issue by DanRamone81** [VCVRack/Rack#1911]
### Details

Operating system and version: MacOS 10.13.6
Rack version (vX.Y.Z): v1.1.6
Hardware relevant to your issue (e.g. graphic card model, audio/MIDI device):

### Summary
My most beloved template is suddenly crashing vcv. I don't know the cause, I tried to reinstall everything, saved the template as a patch, but again if I open it again it will make vcv crash again. I wish I could at least have a list of modules I was using to try to recreate it, but I can't remember all.
### Steps to reproduce
Just open the patch in vcv
[log.txt](https://github.com/VCVRack/Rack/files/6369280/log.txt)

[template-v1.vcv.zip](https://github.com/VCVRack/Rack/files/6369284/template-v1.vcv.zip)

**Comment by cschol** [comment]
Reproduced on GNU/Linux (Ubuntu 20.04).

Stacktrace from debugger:
```
Program terminated with signal SIGABRT, Aborted.
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
50      ../sysdeps/unix/sysv/linux/raise.c: No such file or directory.
[Current thread is 1 (Thread 0x7ff2b751ef00 (LWP 7446))]
(gdb) bt
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
#1  0x00007ffff715e859 in __GI_abort () at abort.c:79
#2  0x00007ffff715e729 in __assert_fail_base (fmt=0x7ffff72f4588 "%s%s%s:%u: %s%sAssertion `%s' failed.\n%n", assertion=0x555555a180e4 "module->id != m->id", file=0x555555a18009 "src/engine/Engine.cpp", line=534, function=<optimized out>) at assert.c:92
#3  0x00007ffff716ff36 in __GI___assert_fail (assertion=assertion@entry=0x555555a180e4 "module->id != m->id", file=file@entry=0x555555a18009 "src/engine/Engine.cpp", line=line@entry=534, function=function@entry=0x555555a17db0 "void rack::engine::Engine::addModule(rack::engine::Module*)") at assert.c:101
#4  0x000055555579995a in rack::engine::Engine::addModule(rack::engine::Module*) (this=0x555556683910, module=<optimized out>) at /usr/include/c++/9/bits/predefined_ops.h:240
#5  0x000055555578dbb9 in rack::app::RackWidget::addModule(rack::app::ModuleWidget*) (this=0x555556b12840, m=0x555558485a20) at src/app/RackWidget.cpp:357
#6  0x000055555578dd45 in rack::app::RackWidget::fromJson(json_t*) (this=0x555556b12840, rootJ=0x555556f09a10) at src/app/RackWidget.cpp:256
#7  0x0000555555722c68 in rack::PatchManager::fromJson(json_t*) (this=0x555556aeb8e0, rootJ=0x555556f09a10) at src/patch.cpp:288
#8  0x0000555555722f67 in rack::PatchManager::load(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >) (this=0x555556aeb8e0, path=...) at src/patch.cpp:188
#9  0x0000555555723965 in rack::PatchManager::init(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >) (this=0x555556aeb8e0, path=...) at /usr/include/c++/9/bits/char_traits.h:300
#10 0x00005555556c0a80 in main(int, char**) (argc=<optimized out>, argv=<optimized out>) at /usr/include/c++/9/bits/basic_string.h:936
(gdb) p m->module->id
warning: RTTI symbol not found for class 'TeleportOutModuleWidget'
warning: RTTI symbol not found for class 'TeleportOutModule'
$4 = 384
(gdb) 
```

So it points to an instance of the `LittleUtils` `TeleportOut` module. I don't see any other `id` of 384 in the patch file. Not sure what's going on. Removing that module with `id` 384 from the patch file (with a text editor), lets me load the patch successfully.

**Comment by DanRamone81** [comment]
thanks a lot it worked!
