### ISSUE TITLE
Windows: Crash when trying to load second instance of plugin

### ISSUE THREAD

**Issue by cschol** [VCVRack/Rack#812]
Operating system(s): Windows
Version if official Rack release, commit hash and/or branch if from source: fc91e0f9afd7043ac54301883051673a8ebcf713

I happened to have two folder of the same plugin inside of `plugins`. When I start Rack, it segfaults with the following backtrace:

```
#0  0x00007ffd7243bcf1 in strlen () from /c/WINDOWS/System32/msvcrt.dll
#1  0x000000000049faf5 in __pformat_puts (s=0xfffffffffffff100 <error: Cannot access memory at address 0xfffffffffffff100>, stream=stream@entry=0x1cefb10) at C:/repo/mingw-w64-crt-git/src/mingw-w64/mingw-w64-crt/stdio/mingw_pformat.c:611
#2  0x00000000004a1130 in __mingw_pformat (flags=flags@entry=24576, dest=dest@entry=0x7ffd7246ea70 <msvcrt!_iob+96>, max=max@entry=0, fmt=0x5685aa <CSWTCH.738+3754> "\" is already loaded, not attempting to load it again",
    fmt@entry=0x5685a0 <CSWTCH.738+3744> "Plugin \"%s\" is already loaded, not attempting to load it again", argv=<optimized out>, argv@entry=0x1cefc28 "") at C:/repo/mingw-w64-crt-git/src/mingw-w64/mingw-w64-crt/stdio/mingw_pformat.c:2533
#3  0x0000000000497a3d in __mingw_vfprintf (stream=0x7ffd7246ea70 <msvcrt!_iob+96>, fmt=fmt@entry=0x5685a0 <CSWTCH.738+3744> "Plugin \"%s\" is already loaded, not attempting to load it again", argv=0x1cefc28 "")
    at C:/repo/mingw-w64-crt-git/src/mingw-w64/mingw-w64-crt/stdio/mingw_vfprintf.c:54
#4  0x00000000004436c4 in vfprintf (__local_argv=<optimized out>, __format=0x5685a0 <CSWTCH.738+3744> "Plugin \"%s\" is already loaded, not attempting to load it again", __stream=<optimized out>)
    at C:/msys64/mingw64/x86_64-w64-mingw32/include/stdio.h:369
#5  rack::warn (format=format@entry=0x5685a0 <CSWTCH.738+3744> "Plugin \"%s\" is already loaded, not attempting to load it again") at src/util/logger.cpp:34
#6  0x00000000004249ec in rack::loadPlugin (path=...) at src/plugin.cpp:106
#7  rack::loadPlugins (path=...) at src/plugin.cpp:127
#8  rack::pluginInit () at src/plugin.cpp:405
#9  0x000000000055dfd8 in main (argc=<optimized out>, argv=<optimized out>) at src/main.cpp:35
```

The problem is in `src/plugin.cpp:106`. The `warn()` call does not have a substitution argument for the `%s`.

```
	// Reject plugin if slug already exists
	for (Plugin *p : gPlugins) {
		if (plugin->slug == p->slug) {
			warn("Plugin \"%s\" is already loaded, not attempting to load it again");
```

Should be:

```
warn("Plugin \"%s\" is already loaded, not attempting to load it again", p->slug.c_str());
```

**Comment by AndrewBelt** [comment]
Thanks! daf57e1
