### ISSUE TITLE
Windows: Rack crash when removing USB audio interface

### ISSUE THREAD

**Issue by cschol** [VCVRack/Rack#895]
Platform: Windows
Source revision: v0.6.0

Removing a USB audio interface while Rack is running leads to a Rack crash.

```
(gdb) bt
#0  0x00007ffc39bb4008 in RaiseException () from /c/WINDOWS/System32/KERNELBASE.dll
#1  0x000000006144d191 in ?? () from /mingw64/bin/libgcc_s_seh-1.dll
#2  0x000000006fd08e58 in ?? () from /mingw64/bin/libstdc++-6.dll
#3  0x000000006760211e in RtApi::error (this=this@entry=0xc7b6340, type=type@entry=RtAudioError::SYSTEM_ERROR) at C:/msys64/home/cschol/src/Rack-cschol/dep/rtaudio/RtAudio.cpp:9490
#4  0x0000000067608d81 in RtApiDs::callbackEvent (this=this@entry=0xc7b6340) at C:/msys64/home/cschol/src/Rack-cschol/dep/rtaudio/RtAudio.cpp:6540
#5  0x00000000676098e1 in callbackHandler (ptr=0xc7b6580) at C:/msys64/home/cschol/src/Rack-cschol/dep/rtaudio/RtAudio.cpp:6593
#6  0x00007ffc3af4a8e6 in msvcrt!_beginthreadex () from /c/WINDOWS/System32/msvcrt.dll
#7  0x00007ffc3af4a9bc in msvcrt!_endthreadex () from /c/WINDOWS/System32/msvcrt.dll
#8  0x00007ffc3aa21fe4 in KERNEL32!BaseThreadInitThunk () from /c/WINDOWS/System32/KERNEL32.DLL
#9  0x00007ffc3ce6efc1 in ntdll!RtlUserThreadStart () from /c/WINDOWS/SYSTEM32/ntdll.dll
```

**Comment by AndrewBelt** [comment]
This is an issue with RtAudio. https://github.com/thestk/rtaudio
